### PR TITLE
✨ add support for time.Time

### PR DESCRIPTION
**Pull request by bouroo**

### CODE REVIEW

**Comment by LukaGiorgadze** [comment]
Thank you @bouroo,
It misses a negative test case and coverage dropped a little bit. I would be happy if you could add one more test case to cover 100%. Or I can add it later not a big deal.

**Comment by bouroo** [comment]
@LukaGiorgadze 
Ah, I'll add test case tomorrow and let you know when all done.

**Comment by bouroo** [comment]
@LukaGiorgadze
`unknowType` test case added

**Review by LukaGiorgadze — APPROVED** [review]

**Comment by bouroo** [comment]
@LukaGiorgadze could you please tag/release this merge?

**Comment by LukaGiorgadze** [comment]
@bouroo Sure will be released this week.

**Pull request merged**
