### PR TITLE
test: add package example

### PR DESCRIPTION
**Pull request by wazazaby**
Hi! 

Just a small pull request that includes a little bit of refactoring :
* use `any` instead of `interface{}` 
* remove an useless `if` statement
* refactor `convertToType` internals to improve readability

And most importantly a package example to demonstrate how to use `gonull` and what it brings to the table.

As there are no exported functions other than `NewNullable` (which is very straightforward and documented), I think that a package-wide example is fine for now. 

I based it off the example that you wrote in the README file.

Let me know if anything bothers you.

Thank you :)

### CODE REVIEW

**Review by LukaGiorgadze — COMMENTED** [review]
Hey @wazazaby, thank you for your contribution in open-source, you are doing an amazing job!
I reviewed your code and it looks good, the only one thing is that moving `example_test.go` in the `examples` directory could be better than placing it in the main package.

Something like:
`examples/json.go`

So, if you could change that, I'm ready to merge.

**Comment by wazazaby** [comment]
Thank you for the review!

Agreed, the example as now been moved to a `examples` package :)

**Comment by wazazaby** [comment]
@LukaGiorgadze the file should actually be named `json_test.go` to be ran properly, I missed it sorry for that. I will open a new PR to fix it.

**Comment by LukaGiorgadze** [comment]
> @LukaGiorgadze the file should actually be named `json_test.go` to be ran properly, I missed it sorry for that. I will open a new PR to fix it.

hah yeah, I merged the PR, feel free to rise a new one!

**Comment by wazazaby** [comment]
[Examples](https://go.dev/blog/examples) are usually runnable like tests and I believe it's a good thing to have them "interactive" instead of a plain text file (the README would suffice in this case).

If you want to keep them that way it's fine tho.

**Comment by LukaGiorgadze** [comment]
> [Examples](https://go.dev/blog/examples) are usually runnable like tests and I believe it's a good thing to have them "interactive" instead of a plain text file (the README would suffice in this case).
> 
> If you want to keep them that way it's fine tho.

nah, never used examples like that before, but frankly not bad for this kind of repo. Feel free to rise PR, i'll approve it 👍

**Comment by wazazaby** [comment]
Great!

**Pull request merged**
